version: "3.9"

services:
  api:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  worker:
    build:
      context: ./backend
    command: celery -A app.core.celery_app worker -Q default,internal_ai,external_news -l info
    env_file: .env
    volumes:
      - ./backend:/code
    depends_on:
      - redis
      - db

  beat:
    build:
      context: ./backend
    command: celery -A app.core.celery_app beat -l info
    env_file: .env
    volumes:
      - ./backend:/code
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bi_project
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
